version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/.devcontainer/docker/workspace/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "php"
        update-types: ["version-update:semver-minor"]
